name: BetterPvP
version: 'v1.0.0'
main: github.betterpvp.BetterPvP
api-version: '1.13'
author: srsstaff_tv, sstudios
website: https://sstudiosdev.github.io/

commands:
  betterpvp:
    description: Main command for BetterPvP
    usage: /betterpvp <subcommand>

permissions:
  betterpvp.reload:
    description: Permission to reload the configuration
    default: op